#!/bin/bash

DEPTH=7

if [ $# -eq 1 ]
then
    DEPTH=$1
fi

find . -maxdepth $DEPTH | grep -v "\/\." | sort | awk '!/\.$/ {for (i = 1; i < NF; i++) {d = 0; if (i != 1) d = 4; printf("%"d"s", "|");} if(i == 1) {print $NF;} else {print "---"$NF;}}' FS='/'

